Use ESA dependency and features-bom
BriannaLi/guide-cors pull request #1
Opened 2018-09-05 15:31 UTC by BriannaLi

This pull request updates the project pom.xml file to replace all the dependencies with imported scope with the esa feature dependencies, and provides an alternative to use openliberty-kernel runtime with only the required features installed from the esa feature dependencies using the Liberty Maven plugin install-feature goal.

The esa feature dependency will automatically pull the feature's spec api, server api/spi dependencies for building the project.

2018-09-05 15:37 UTC, BriannaLi commented on finish/pom.xml
> +    </repositories>
Plz remove the repo,

2018-09-05 15:37 UTC, BriannaLi commented on finish/pom.xml
> +                <version>18.0.0.3</version>
The version should be RELEASE,

2018-09-05 15:37 UTC, BriannaLi commented on finish/pom.xml
> +                <version>18.0.0.3</version>
Does the code works when the version is not 18003?

2018-09-05 15:37 UTC, BriannaLi commented on start/pom.xml
> +    </repositories>
It seems we don't need the repo right now

2018-09-05 19:25 UTC, patricktiu requested changes

2018-09-05 19:25 UTC, patricktiu commented on finish/pom.xml
>          <dependency>
The next 4 dependencies should have a cope of test. ```<scope>test</scope>```

2018-09-05 19:25 UTC, patricktiu commented on start/pom.xml
>          <dependency>
he next 4 dependencies should have a cope of test. ```<scope>test</scope>```

2018-09-06 18:14 UTC, zhangm13 commented on finish/pom.xml
>          <dependency>
Resolved. I have added that in to the latest commit.

2018-09-06 18:15 UTC, zhangm13 commented on start/pom.xml
>          <dependency>
Resolved. Added to the dependencies

2018-09-06 19:21 UTC, patricktiu approved these changes

2018-09-06 20:08 UTC, merged